=== GeoLabs/bblocks-openeo/build/annotated/openeo/processes/cubes/load_collection/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Load a collection",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "https://raw.githubusercontent.com/GeoLabs/bblocks-openeo/undefined/build/annotated/openeo/types/collection-id/schema.json"
    },
    "spatial_extent": {
      "anyOf": [
        {
          "$ref": "https://raw.githubusercontent.com/GeoLabs/bblocks-openeo/undefined/build/annotated/openeo/types/bounding-box/schema.json"
        },
        {
          "$ref": "https://raw.githubusercontent.com/GeoLabs/bblocks-openeo/undefined/build/annotated/openeo/types/geojson/schema.json",
          "deprecated": true
        },
        {
          "$ref": "https://raw.githubusercontent.com/GeoLabs/bblocks-openeo/undefined/build/annotated/openeo/types/datacube/schema.json"
        },
        {
          "title": "No filter",
          "description": "Don't filter spatially. All data is included in the data cube.",
          "type": "null"
        }
      ]
    },
    "temporal_extent": {
      "anyOf": [
        {
          "$ref": "https://raw.githubusercontent.com/GeoLabs/bblocks-openeo/undefined/build/annotated/openeo/types/temporal-interval/schema.json"
        },
        {
          "title": "No filter",
          "description": "Don't filter temporally. All data is included in the data cube.",
          "type": "null"
        }
      ]
    },
    "bands": {
      "anyOf": [
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "https://raw.githubusercontent.com/GeoLabs/bblocks-openeo/undefined/build/annotated/openeo/types/band-name/schema.json"
          }
        },
        {
          "title": "No filter",
          "description": "Don't filter bands. All bands are included in the data cube.",
          "type": "null"
        }
      ]
    },
    "properties": {
      "anyOf": [
        {
          "$ref": "https://raw.githubusercontent.com/GeoLabs/bblocks-openeo/undefined/build/annotated/openeo/types/metadata-filter/schema.json"
        },
        {
          "title": "No filter",
          "description": "Don't filter by metadata properties.",
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "id",
    "spatial_extent",
    "temporal_extent"
  ]
}

=== GeoLabs/bblocks-openeo/build/tests/openeo/processes/cubes/load_collection/example_1_1.json
{
  "id": "Sentinel-2",
  "spatial_extent": {
    "west": 16.1,
    "east": 16.6,
    "north": 48.6,
    "south": 47.2
  },
  "temporal_extent": [
    "2018-01-01",
    "2019-01-01"
  ],
  "properties": {
    "eo:cloud_cover": {
      "process_graph": {
        "cc": {
          "process_id": "between",
          "arguments": {
            "x": {
              "from_parameter": "value"
            },
            "min": 0,
            "max": 50
          },
          "result": true
        }
      }
    },
    "platform": {
      "process_graph": {
        "pf": {
          "process_id": "eq",
          "arguments": {
            "x": {
              "from_parameter": "value"
            },
            "y": "Sentinel-2B",
            "case_sensitive": false
          },
          "result": true
        }
      }
    }
  }
}
